name: js-parser

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: ./js-parser/package-lock.json

      - name: Test js parser.
        working-directory: ./js-parser
        run: |
          npm ci
          npm run test:coverage
