name: js-parser

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Test js parser.
        working-directory: ./js-parser
        run: |
          npm ci
          npm run test:coverage
