name: parser-js-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code.
      - uses: actions/checkout@v2

      # Run on Node.js 14.x
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # Cache npm dependencies as long as os and package-lock.json do not change.
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Test js parser.
      - name: Install dependencies and test parser.
        working-directory: ./study-project/parser-js
        run: |
          npm ci
          npm test
        env:
          CI: true
